imports:
  - resource: UserServices.yml
  - resource: TrainingServices.yml
  - resource: DayServices.yml
  - resource: VoterServices.yml
  - resource: CurrentUserServices.yml
  - resource: StatusServices.yml
  - resource: ChallengeServices.yml
  - resource: ParticipantService.yml
