security:
    encoders:
        CoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        webservice:
            id: guard_bundle.webservice_user_provider

    firewalls:
        dev:
            pattern: ^/_wdt
            security: false

        api_doc:
            pattern: ^/doc
            security: false

        register:
            pattern: ^/api/register
            security: false

        voting:
            pattern: ^/api/voting*
            security: false

        challenge:
            pattern: ^/api/challenge*
            methods: [GET]
            security: false

        participant:
            pattern: ^/api/participant*
            methods: [GET]
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            guard:
                authenticators:
                    - guard_bundle.password_authenticator

        main:
            pattern: ^/
            stateless: true
            guard:
                authenticators:
                    - guard_bundle.token_authenticator

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/api/(trainings|challenge|participant|user), roles: ROLE_ADMIN }