security:
    providers:
        user_provider:
            entity:
                class: CoreBundle\Entity\User
                property: name

    firewalls:
        login:
            pattern: ^/api/login
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        dev:
            pattern: ^/_wdt
            security: false

        api_doc:
            pattern: ^/doc
            anonymous: true

        voting:
            pattern: ^/api/votes*
            methods: [GET]
            security: false

        challenge:
            pattern: ^/api/challenge*
            methods: [GET]
            security: false

        participant:
            pattern: ^/api/participant*
            methods: [GET]
            security: false

        api:
            pattern:   ^/api
            stateless: true
            provider: user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            anonymous: ~

    access_control:
        - { path: ^/api/(participant|user), roles: ROLE_ADMIN }