api_user:
  resource: '@ApiBundle/Controller/UserController.php'
  type: rest
  prefix: /api
  defaults:
    _format: json
api_training:
  resource: '@ApiBundle/Controller/TrainingController.php'
  type: rest
  prefix: /api
  defaults:
    _format: json
api_voter:
  resource: '@ApiBundle/Controller/VoterController.php'
  type: rest
  prefix: /api
  defaults:
    _format: json