api_user:
  resource: '@ApiBundle/Controller/UserController.php'
  type: rest
  prefix: /api
  defaults:
    _format: json
api_training:
  resource: '@ApiBundle/Controller/TrainingController.php'
  type: rest
  prefix: /api
  defaults:
    _format: json
api_vote:
  resource: '@ApiBundle/Controller/VoteController.php'
  type: rest
  prefix: /api
  defaults:
    _format: json
api_current_user:
  resource: '@ApiBundle/Controller/CurrentUserController.php'
  type: rest
  prefix: /api
  defaults:
    _format: json
api_challenge:
  resource: '@ApiBundle/Controller/ChallengeController.php'
  type: rest
  prefix: /api
  defaults:
    _format: json
api_participant:
  resource: '@ApiBundle/Controller/ParticipantController.php'
  type: rest
  prefix: /api
  defaults:
    _format: json
api_ldap_authorization:
  resource: '@ApiBundle/Controller/LDAPAuthorizationController.php'
  type: rest
  prefix: /api
  defaults:
    _format: json